apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver
  namespace: labuk-spark-jobs

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: labuk-spark-jobs
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]  # add status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rolebinding
  namespace: labuk-spark-jobs
subjects:
  - kind: ServiceAccount
    name: spark-driver
    namespace: labuk-spark-jobs
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io
